# Generated by Django 4.2.4 on 2023-09-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_model', models.CharField(max_length=255, unique=True)),
                ('product_name', models.CharField(max_length=255)),
                ('image_path', models.CharField(max_length=512)),
                ('product_type', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('positive_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('negative_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('specifications', models.JSONField()),
            ],
        ),
    ]
