# Generated by Django 4.2.4 on 2023-09-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='positive_percentage',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=5),
        ),
    ]
